---
title: "Violet Zone ES Magnet Options"
output: 
    html_document:
        code_folding: hide
---

# Options Map
I just became aware of the CMS Magnet process and options for the
  upcoming lottery. As a parent of a Blythe Elem. 2nd grader, I was
  given a list of 13 schools that I could rank as choices for our
  child. (Note, this list of schools may vary based on student test
  scores or other factors. Don¡¯t assume these are your lottery
  options.)

After bouncing around the web collecting information on the potential
magnet options, I pulled together the visualization below. Basically,
just a map of the schools, each hyperlinked with the school¡¯s website
and some info from the NC School Report Cards website.

**NOTE: This is a quick personal project, which you should not rely on
for accurary or completeness. I don¡¯t work for or represent CMS in
anyway. Any questions about the CMS Lottery process should be directed
to CMS.**

**Also, I haven¡¯t looked into how ¡°School Grades¡± or ¡°Growth
Expectations¡± are determined. You should do your own research on their
strengths and deficiencies before relying on them for anything.**
          
## Data
```{r}
rm(list=ls())
library(leaflet)
library(rmarkdown)
library(dplyr)

## load data
ds <- read.table(file="schoolData.csv", sep=",", row.names=NULL,
                 stringsAsFactors=FALSE, header=TRUE)
ds$grade.17 <- paste("2017 Grade:", ds$grade.17)
ds$growth17 <- paste("2017 Growth:", ds$growth17)
ds$links <- paste0("<a href='",ds$link,"'>",ds$school,"</a>")
ds$link2 <- paste0("<a href='",ds$link2,"'>",
                   "School Report Cards Site","</a>")

ds$img <- paste0("<a href='",ds$img,".PNG","'>",
                 "Grades Excerpt","</a>")

p1 <- leaflet(width="100%") %>%
    addProviderTiles(providers$OpenStreetMap.Mapnik) %>%
    setView(lng = -80.845, lat = 35.296, zoom = 11) %>%
    addMarkers(lng=ds$long, lat=ds$lat,
               popup=paste(sep="<br/>", ds$links, ds$grade.17,
                           ds$growth17, ds$img, ds$link2))

p1

```
        
